variables:
  CARGO_HOME: "$CI_PROJECT_DIR/.cargo"

image: "python:3.8"

cache:
  paths:
  - .cargo
  - target/

stages:
  - build
  - lint
  - test
  - deploy


lint:python:
  stage: lint

  before_script:
    - pip install flake8
  script:
    - flake8 corona_connect.py


test:python:
  stage: test

  before_script:
    - pip install pytest
  script:
    - pytest tests/


deploy:serverless:
  image: "node:latest"
  stage: deploy
  only:
  - master
  environment:
    name: production
    url: "https://7xbv26cd6k.execute-api.eu-central-1.amazonaws.com/production/"
  cache:
    paths:
    - node_modules/
    - .serverless/
  before_script:
  - npm install
  script:
  - npx serverless deploy --stage production
