variables:
  CARGO_HOME: "$CI_PROJECT_DIR/.cargo"

image: "rust:1.41.0"

cache:
  paths:
  - .cargo
  - target/

stages:
  - build
  - lint
  - test
  - deploy


build:cargo:
  image: "rust:latest"
  stage: build

  script:
  - rustc --version && cargo --version  # Print version info for debugging
  - cargo build --all

  artifacts:
    paths:
    - target/


lint:cargo:
  image: "rust:latest"
  stage: lint

  before_script:
  - rustup component add clippy
  script:
  - cargo clippy


test:cargo:
  image: "rust:latest"
  stage: test
  
  script:
  - rustc --version && cargo --version  # Print version info for debugging
  - cargo test --all --verbose


deploy:serverless:
  image: "docker:latest"
  stage: deploy
  services:
  - docker:19.03.1-dind
  only:
  - master
  environment:
    name: production
    url: "https://7xbv26cd6k.execute-api.eu-central-1.amazonaws.com/production/"
  cache:
    paths:
    - node_modules/
    - target/
    - .serverless/
  before_script:
  - apk add npm
  - npm install
  script:
  - npx serverless deploy --stage production
