# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!
service: coco-api
provider:
  name: aws
  runtime: python3.7
  memorySize: 128
  region: eu-central-1
  environment:
    DB_HOST: 
      Fn::GetAtt: ["helperDatabase", "Endpoint.Address"]
    DB_USER: ${env:POSTGRES_MASTER_USER, 'postgres'}
    DB_PASSWORD: ${env:POSTGRES_MASTER_PASSWORD}
    DATABASE_URL:
      Fn::Join:
        - ""
        - ["postgres://${env:POSTGRES_MASTER_USER, 'postgres'}:${env:POSTGRES_MASTER_PASSWORD}@", Fn::GetAtt: ["helperDatabase", "Endpoint.Address"], "/postgres" ]

plugins:
  - serverless-python-requirements
      
package:
  exclude:
    - .envrc
    - venv

functions:
  register:
    # handler value syntax is `{cargo-package-name}.{bin-name}`
    # or `{cargo-package-name}` for short when you are building a
    # default bin for a given package.
    handler: corona_connect.register
    events:
      - http:
          path: '/register'
          method: POST
          request:
            schema:
              application/json: ${file(schema/create_user.json)}


  phone:
    handler: corona_connect.phone
    events:
      - http:
          path: '/phone'
          method: GET


# you can add CloudFormation resource templates here
resources:
  Resources:
    helperDatabase:
      Type: AWS::RDS::DBInstance
      Properties:
        DBInstanceClass: db.t2.micro
        AllocatedStorage: 20
        Engine: postgres
        MasterUsername: postgres
        MasterUserPassword: ${env:POSTGRES_MASTER_PASSWORD}
